<?php

namespace TDN\NanaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NanaHobbyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NanaHobbyRepository extends EntityRepository
{
}
