<?php

namespace TDN\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilQuizRepository extends EntityRepository
{
}
