<?php

namespace TDN\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends EntityRepository
{
		public function findLast ()
		{
			$qb = $this->createQueryBuilder('c');
			$query = $qb->select('c')
				->where($qb->expr()->like('c.statut', $qb->expr()->literal('QUIZ_PUBLIE')))
				->orderby('c.datePublication', 'DESC')
				->setMaxResults(1)
				->getQuery();

			return $query->getResult();
		}
}
