<?php

namespace TDN\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
	public function findSelection ($limite) {
		$qb = $this->createQueryBuilder('s'); 
		$q = $qb->select('s')
				->where($qb->expr()->andX(
       				$qb->expr()->eq('s.statut', '1'),
       				$qb->expr()->lte('s.datePublication', ':now')))
				->setParameter('now', new \DateTime)
				->orderBy('s.ordre', 'DESC')
				->addOrderBy('s.idSlide', 'DESC')
				->setMaxResults($limite)
				->getQuery()
				->useResultCache(true, 3600);

		return $q->getResult();
	}

	public function getFeatured ($limite) {
		$qb = $this->createQueryBuilder('s'); 
		$q = $qb->select('s', 'd')
				->innerjoin('s.lnSource', 'd')
				->where($qb->expr()->andX(
       				$qb->expr()->eq('s.statut', '1'),
       				$qb->expr()->lte('s.datePublication', ':now'),
       				$qb->expr()->like('d.statut', ':statut')))
				->setParameter('now', new \DateTime)
				->setParameter('statut', 'ARTICLE_PUBLIE')
				->orderBy('s.ordre', 'DESC')
				->addOrderBy('s.idSlide', 'DESC')
				->setMaxResults($limite)
				->getQuery()
				->useResultCache(true, 3600);

		return $q->getResult();
	}
}
