<?php

namespace TDN\ConseilExpertBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LegacyController__JMSInjector
{
    public static function inject($container) {
        $instance = new \TDN\ConseilExpertBundle\Controller\LegacyController();
        return $instance;
    }
}
