<?php

namespace TDN\CoreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HeaderController__JMSInjector
{
    public static function inject($container) {
        $instance = new \TDN\CoreBundle\Controller\HeaderController();
        return $instance;
    }
}
