<?php

namespace TDN\NanaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PublicController__JMSInjector
{
    public static function inject($container) {
        $instance = new \TDN\NanaBundle\Controller\PublicController();
        return $instance;
    }
}
