<?php

namespace TDN\RedactionBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminShoppingController__JMSInjector
{
    public static function inject($container) {
        $instance = new \TDN\RedactionBundle\Controller\AdminShoppingController();
        return $instance;
    }
}
